### PR TITLE
update engage cmd

### PR DESCRIPTION
**Pull request by BloodEko**
adds https://github.com/DenizenScript/Denizen-For-Bukkit/issues/1735

### CODE REVIEW

**Comment by mcmonkey4eva** [comment]
Poorly implemented, misformatted, and no IDE usage... yeah nope.

**Comment by BloodEko** [comment]
Formatting can be fixed. Could you please tell me, what you mean by "Poorly implemented" in aspects of design and or performance to the code I presented here?

**Comment by mcmonkey4eva** [comment]
As I've written repeatedly on Discord: You do not ever listen to replies or try to learn from code corrections. There's no point in us continuing to try explaining how anything works to you.

**Comment by BloodEko** [comment]
Out of your last post goes no helpful information to answer my question from my last post, instead you are referencing on excuses.

**Comment by mcmonkey4eva** [comment]
It is not worth my time to answer your questions when you have shown time after time that you don't learn anything after any of my (or anyone else's) attempts to help you.

**Pull request closed without merging**
