### PR TITLE
Fix stuff like bad meta and bad entity mgmt

### PR DESCRIPTION
**Pull request by Talamar1**

### CODE REVIEW

**Comment by Talamar1** [comment]
not sure if changing the "time" to datestamp or something would make it even more clear

**Comment by mcmonkey4eva** [comment]
```
[08:25:02] <monkeybot> Found: <d@duration.in_milliseconds>, which returns a Element(Decimal)
[08:25:02] <monkeybot>   returns the number of milliseconds in the Duration.
```

**Comment by Talamar1** [comment]
looking at the code:
`        if (attribute.startsWith("last_played")) {
            attribute = attribute.fulfill(1);
            if (attribute.startsWith("milliseconds") || attribute.startsWith("in_milliseconds"))
                return new Element(getOfflinePlayer().getLastPlayed())
                        .getAttribute(attribute.fulfill(1));
            else
                return new Duration(getOfflinePlayer().getLastPlayed() / 50)
                        .getAttribute(attribute);
        }
`
in_milliseconds is being handled by player.last_played, not by duration.in_milliseconds

**Comment by mcmonkey4eva** [comment]
Yes - it's being manually handled to dodge inaccuracy. Nonetheless, this PR defines meta for the same thing twice.

**Pull request closed without merging**
