### PR TITLE
handle offhand in clicks block event

### PR DESCRIPTION
**Pull request by mergu**
Fixes https://github.com/DenizenScript/Denizen-For-Bukkit/issues/1619

### CODE REVIEW

**Comment by mcmonkey4eva** [comment]
If it's not specified either way, maybe... only fire of default hand, and have an option for `either_hand`?

**Comment by mergu** [comment]
Turning the event into a script event to accomplish that, it's nearly complete. Also, committed a fix for https://github.com/DenizenScript/Denizen-For-Bukkit/issues/1639

**Comment by mcmonkey4eva** [comment]
Fabulous!

**Comment by SaitDev** [comment]
Plz make it works for right click event too. Great job!

**Comment by mergu** [comment]
This already works for generic, left, and right clicks. Join us on discord if you need some help!
https://discord.gg/Q6pZGSR

**Comment by SaitDev** [comment]
Oh sorry. my bad. Tried wrong event

**Pull request merged**
