### PR TITLE
A creative artistic title.

### PR DESCRIPTION
**Pull request by Fortifier42**

### CODE REVIEW

**Comment by Fortifier42** [comment]
Yes, but @Talamar1 had a bitch fit.

**Comment by mcmonkey4eva** [comment]
And Talamar is to be trusted because....?

**Comment by Talamar1** [comment]
Bool·e·an
ˈbo͞olēən/
adjective

1.
a binary variable, having two possible values called “true” and “false.”

Computer Science 101, there are only 2 boolean values, null is not a valid value.  
- if <boolean> { } 

null is not valid, this really is simple.  You can't do it in Java, C, C++ or any sane language, why would you do it here?

**Comment by Fortifier42** [comment]
@Talamar1 invalid input results in invalid output, regardless of designated output type. Take any other tag..

**Comment by Talamar1** [comment]
Then throw an error and crash the script, don't return a value that can't be used.

**Comment by Fortifier42** [comment]
that's technically what null does

**Comment by Fortifier42** [comment]
it returns null not "null" there is a difference.

**Comment by Talamar1** [comment]
Here is a tag, returns false when material is invalid (did a valueof and never actually checked to see if they got a valid value.... O.o ):
```
        // <--[tag]
        // @attribute <in@inventory.contains.material[<material>]>
        // @returns Element(Boolean)
        // @description
        // Returns whether the inventory contains an item with the specified material.
        // -->
        if (attribute.startsWith("contains.material")) {
            if (attribute.hasContext(2)) {
                int qty = 1;
                int attribs = 2;
                dMaterial material = dMaterial.valueOf(attribute.getContext(2));

                // <--[tag]
                // @attribute <in@inventory.contains.material[<material>].quantity[<#>]>
                // @returns Element(Boolean)
                // @description
                // Returns whether the inventory contains a certain quantity of an item with the
                // specified material.
                // -->
                if ((attribute.getAttribute(3).startsWith("quantity") || attribute.getAttribute(3).startsWith("qty")) &&
                        attribute.hasContext(3) &&
                        aH.matchesInteger(attribute.getContext(3))) {
                    qty = attribute.getIntContext(3);
                    attribs = 3;
                }

                int found_items = 0;

                for (ItemStack item : getContents()) {
                    if (item != null && item.getType() == material.getMaterial()) {
                        found_items += item.getAmount();
                        if (found_items >= qty) break;
                    }
                }

                return (found_items >= qty ? Element.TRUE.getAttribute(attribute.fulfill(attribs))
                        : Element.FALSE.getAttribute(attribute.fulfill(attribs)));
            }
        }
```

**Comment by Fortifier42** [comment]
`if (item != null && item.getType() == material.getMaterial()) {`

**Comment by Talamar1** [comment]
That checks to see if the item is null, not the material.  There is only one return statement in the whole piece of code and it returns either TRUE or FALSE.

**Comment by Fortifier42** [comment]
if a single argument of an if val && val returns false, it will ignore the rest of the if statement...

**Comment by Talamar1** [comment]
I'm not sure why this is relative to the conversation about return values.

**Pull request merged**
