### PR TITLE
Dun dunn dunnn

### PR DESCRIPTION
**Pull request by Fortifier42**

### CODE REVIEW

**Comment by mcmonkey4eva** [comment]
wtf is this

**Comment by Fortifier42** [comment]
Code cleaning :tongue:

**Comment by mcmonkey4eva** [comment]
and how many merges were required to clean code

**Comment by Fortifier42** [comment]
You didn't merge the pull request when I actually submitted it

**Comment by mcmonkey4eva** [comment]
lrn2github

**Comment by Fortifier42** [comment]
Lrn2dostuff

**Comment by mcmonkey4eva** [comment]
Feel free to resubmit without merge spam.

**Pull request closed without merging**
