### PR TITLE
improve - run parsing

### PR DESCRIPTION
**Pull request by BloodEko**
This changes the order to a more likely one, which reduces the total amount of checks per run.

It also groups the as: argument, cause the matchesPrefix check is made 3 times for no reason.

### CODE REVIEW

**Comment by mcmonkey4eva** [comment]
Reordering that block doesn't help much of anything. Grouping the as block could though.

**Comment by BloodEko** [comment]
For a simple call `- run myScript` the ordner actually doesn't matter, as you said.
I had in mind stuff like `- run myScript def:1` , where some else if else if checks are skripped, when the most likely entries are at the top.

iteration 1: (myScript)
no difference

iteration 2: (def:1)
start -> id -> as -> as -> as -> def

start -> def

**Comment by mcmonkey4eva** [comment]
Still not a remotely noteworthy or worthwhile improvement.

**Comment by BloodEko** [comment]
Yes. it's just a small improvement, actually not so much to say.
The idea was to reward all people, that use lot's of own functions/task scripts with a bit more speed.
(`- run ` can be one of the most used commands ( i.e. used 500+ times for my server) )

By thinking about it: The idea of optimizing default cases could be applied probably for other commands and other stuff too. I had just `- run` in mind yet.

**Comment by mcmonkey4eva** [comment]
It's a nonsense optimization either way.
It's just a commit for the sake of a commit.
As an example of why (non-real numbers, but reasonably close to the real proportions involved)
If each run command takes 2 ms to run, give or take half a millisecond, and your optimization improves it by `0.01` ms... your optimization did nothing, realistically. It wasn't needed and it just reorganized the code and screwed with the git history for no real benefit.

**Pull request closed without merging**
