### PR TITLE
Implement client-side world borders

### PR DESCRIPTION
**Pull request by mergu**

### CODE REVIEW

**Comment by MusicScore** [comment]
I think that `curr_size` should be `from_size` for more clarity. It isn't immediately obvious what `curr_size` means or does.

**Comment by mergu** [comment]
I disagree - curr_size is the current size of the world border.

If that's acceptance criteria then I'll change the name, but for now that feels silly.

**Comment by mcmonkey4eva** [comment]
I don't like `curr_size` because `curr` isn't a word and thus maybe isn't ideal for user-facing stuff - `current_size` or as Suspic wrote `from_size` or anything else that reduces the risk of "what does that word even mean" user responses would be ideal.

Also regardless of the name there should ideally be documentation saying what it is (and also for the rest of the options available for that matter, though if you don't care to write docs for the others I'd appreciate just leaving a `TODO` noting that).
Just a little series of notes in the description like `Optionally specify 'current_size' to indicate a size to start expanding from when used with a new 'size' value and an expansion 'duration' value.` to describe the current_size parameter (and then similar lines explaining the other parameters).

**Comment by mcmonkey4eva** [comment]
Solid.
Thanks!
And extra thanks for adding all the additional docs!

**Pull request merged**
