### PR TITLE
Change old "on player clicks/player stands on" to new scriptEvent format

### PR DESCRIPTION
**Pull request by Talamar1**

### CODE REVIEW

**Comment by mcmonkey4eva** [comment]
@Talamar1 this is unmergeable please fix.

**Comment by Morphan1** [comment]
:+1: does it work?

**Comment by Talamar1** [comment]
Yes?  The only conflict was mcmonkey changing a default from null to AIR, which is weird because he then overwrote it with another call before he even used it, so that edit seemed worthless and just caused an issue for no apparent reason.

**Comment by Talamar1** [comment]
I'm not sure that Craftitem works the way people think it does.  If I craft an item and take qty 1 from the result, it refires immediately because the remaining items are "recrafted".

**Comment by mcmonkey4eva** [comment]
Please 2 squash. 11 commits wot.

**Comment by mcmonkey4eva** [comment]
@Talamar1 pls

**Pull request closed without merging**
