### PR TITLE
Target entities through all non-solid blocks

### PR DESCRIPTION
**Pull request by mergu**
Fixes https://github.com/DenizenScript/Denizen-For-Bukkit/issues/1783

### CODE REVIEW

**Comment by Morphan1** [comment]
I don't know if they ever fixed it, but last I checked Bukkit's isSolid was unreliable. For example, you can walk and see through  blocks where levers are, but it still counts them as solid

**Comment by mcmonkey4eva** [comment]
Was discussing that about 30 minutes ago in the discord - according to mergu, isSolid is much much more trustworthy than it used to be, and our alternative isSafeBlock thing (made originally by mythan forever ago) is now the outdated/bad option

**Comment by mergu** [comment]
Yep, also willing to switch <player.target> to ignore all non-occluding blocks. Up to you all.
https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html#isOccluding--

**Comment by mcmonkey4eva** [comment]
I don't think occluding would be a valid replacement there - target should try to match the logic of a punch, which is based on solidity, not visuals

**Comment by Morphan1** [comment]
Alright then, seems *solid* to me

**Pull request merged**
